

package problem2;

/**
 *
 * @author QingbaoGuo
 */
public class Main {
    /*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
   By starting with 1 and 2, the first 10 terms will be:
   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence
     whose values do not exceed four million,
     find the sum of the even-valued terms.
	 Answer: 4613732
       *
       */
    
    public static void main(String[] args) {
        int F [] = new int [34];
        F[0] = 0;
        F[1] = 1;
        int f = 0;
        int sum =0;
        for (int i = 2;i<=33;i++){
          F[i] = F[i-1] + F[i-2];
          f = F[i];
          if(f <= 4000000 && f%2 ==0){
          sum = sum + f;
          System.out.println(f+"   "+sum);
            }
        }


        

        
    }

}
